apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: buffer
  name: analyze-app
  labels:
    app: analyze
    service: app
    track: stable
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: analyze
        service: app
        track: stable
    spec:
      containers:
      - name: analyze-app
        image: bufferapp/buffer-analyze:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 150Mi
      imagePullSecrets:
        - name: dhbufferapp
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: analyze-app
  namespace: buffer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:980620087509:certificate/823c1d82-bbdd-4a3b-b1b3-e0a78e5ba6ff
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  labels:
    app: analyze
    service: web
    track: stable
spec:
  ports:
    - port: 443
      targetPort: 80
      protocol: TCP
      name: https
  selector:
    app: analyze
    service: app
  type: LoadBalancer
